name: blog_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    
  flutter_screenutil: ^5.9.3 
  firebase_auth: ^5.5.1 
  cloud_firestore: ^5.6.5 
  firebase_core: ^3.12.1 
  fluttertoast: ^8.2.12 
  firebase_storage: ^12.4.4 
  image_picker: ^1.1.2 
  uuid: ^4.5.1 
  image: ^4.5.4 
  url_launcher: ^6.3.1
  file: ^7.0.1
  get: ^4.7.2
  connectivity_plus: ^6.1.3
  flutter_plugin_android_lifecycle: ^2.0.27
    


dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
  lint: ^2.8.0

flutter: 
  uses-material-design: true

assets:
  - assets/images/logo.png
